apiVersion: v1
kind: Service
metadata:
  name: playwright-tests-service
  namespace: default
spec:
  selector:
    app: playwright-tests
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
